# Javascript Node CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.5

    steps:
      - checkout

      - run:
          name: "Installing dependencies"
          command: yarn

      - run: yarn lint

      - run: yarn test --verbose --coverage

      - run: 
          name: "Building and deploying"
          command: |
           if [[ "${CIRCLE_BRANCH}" == 'master'] || ["${CIRCLE_BRANCH}" == 'dev' ]]; then
            CI=false yarn deploy $CIRCLE_BRANCH
           else
            CI=false yarn package alpha
           end;
            
      - run: CI=false yarn deploy $CIRCLE_BRANCH

      - store_artifacts:
          path: build/grid-ui*.zip

      - store_artifacts:
          path: build/manifest.json


workflows:
  version: 2
  commit:
    jobs:
      - build
